### ISSUE TITLE
Help! Apply the patch file to wildfly 11

### ISSUE THREAD

**Issue by jedwar** [marco76/java-demo#13]
Hi Marco, 
Please, I need your help ... I following the steps in the link share, I downloaded:
1. wildfly-11.0.0.Alpha1.zip  and
2. hibernate-validator-6.0.0.Alpha2-dist.zip
to apply the patch the command requiere  "... hibernate-validator-modules-6.0.0.Alpha2-wildfly-10.1.0.Final-patch.zip". How I can create the patch file? Do you downloaded it? I was reviwing and exist one tool to create patch file for WildFly. Do you use this tool??, thanks 

Edwar

**Comment by marco76** [comment]
Hi Edwar,

Sorry for the late reply, I didn't get the notification from GitHub.
The patch files are for the official version of Wildfly (10.1, http://wildfly.org/downloads/) and not for wildfly 11.
Previously I did my own patch for Wildfly 11 but now I stick with the official one.
BV: http://in.relation.to/2017/04/04/testing-bean-validation-2-0-on-wildfly-10/
You should add the CDI 2.0 patch too: http://weld.cdi-spec.org/news/2017/03/03/weld-300CR2/

You can find here a description about how to apply the patches: http://weld.cdi-spec.org/documentation/#12
In few words:
1. you download wildfly 10.1
2. you download the CDI and BV patches
3. start wildfly
4. use jboss-cli.bat to run the *.zip patches as described in the previous link

I will try to show this step by step in the docker script when I've a bit of time.
Let me know if you succeed.

Marco

**Comment by marco76** [comment]
No news. I close the issue.

**Comment by jedwar** [comment]
Hi Marco, sorry .. the last days I was very busy ... by the way, today I saw your project again ... In the version shared I found some bug's in the client ... with the ngx-bootstrap library I update the file "app.module.ts" al all compiled.
The second problem was the wildfly 10.1, I apply the CDI patch it was the easy step ... but the BV there isn't one patch compiled ... then I compiled all the project BV and use the "hv-patch.zip".
the third issue was the datasource ... do you use H2 DB for develop?? My deploy process fail because the doesn't create the DB ... well I'm reviewing the datasources and the code.
Finally I review your docker file and all executed very well with the image, then I download your wildfly version ... but I have the same error message with the data source ... i think that you are using one embedded h2 db, because in the docker file you don't  register the datasource with the UserDB bean.
I'll continue reviewing the issues ... regards, jesus

**Comment by jedwar** [comment]
Hi Marco, sorry .. the last days I was very busy ... by the way, today I
saw your project again ... In the version shared I found some bug's in the
client ... with the ngx-bootstrap library I update the file "app.module.ts"
al all compiled.
The second problem was the wildfly 10.1, I apply the CDI patch it was the
easy step ... but the BV there isn't one patch compiled ... then I compiled
all the project BV and use the "hv-patch.zip".
the third issue was the datasource ... do you use H2 DB for develop?? My
deploy process fail because the doesn't create the DB ... well I'm
reviewing the datasources and the code.
Finally I review your docker file and all executed very well with the
image, then I download your wildfly version ... but I have the same error
message with the data source ... i think that you are using one embedded h2
db, because in the docker file you don't register the datasource with the
UserDB bean.
I'll continue reviewing the issues ... regards, jesus

Saludos desde Lima - Peru !!!

**Comment by marco76** [comment]
Hi Jesus,

Many thanks for the review :)

You are right for ngx-bootstrap the library changed name, I updated it in my local version (and deployed one on the website) but I didn’t upgrade yet the GitHub version.
It’s a kind of nightly development and I don’t have much time neither. The goal is to have something ready when Java EE 8 comes out (it will take a while before the application servers will be ready ;)).
For BV I followed the same procedure as for CDI and I had no problems.

You are right, the datasource has to be configured in standalone.xml of WildFly, the goal is to have a DB that doesn’t need to be installed and H2 is delivered with WildFly.
<datasource jndi-name="java:jboss/datasources/DemoDS" pool-name="DemoDS" enabled="true" use-java-context="true">
                    <connection-url>jdbc:h2:file:~/db/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE</connection-url>
                    <driver>h2</driver>
                    <security>
                        <user-name>sa</user-name>
                        <password>sa</password>
                    </security>
                </datasource>

I don’t thought that many developers will try to install patches etc. to try the demo on their own laptop so I didn’t spend too much time documenting it ;) 

The docker file is an old version, WildFly was patched WildFly (only with BV) and uploaded on AWS. It doesn’t have the CDI patch or the DB config. I could prepare a version that automatically patch WildFly and configure the datasource, but at this point of the development process of the specs I think it’s a lot of work for nothing.
When GlassFish or Payara will integrate the new BV and CDI I will move the dev to GF/Payara.

Thanks again for your help! :)

Regards

Marco

**Comment by jedwar** [comment]
Hi Marco,
Finally I executed all the code successfully client and server, now I'm
focus in the code to test the new features of Java EE 8, thanks for you
support.
I'll send you my observations about the code as soon as possible, see you.

Regards

**Comment by marco76** [comment]
Hi Jesus,
Thanks, no need to hurry. I will fix the docker install so the demo will be easily accessible.

Cheers

Marco
